config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'groups#index'
  end

  root to: 'pages#home'

  post "yammer", to: "users/omniauth_callbacks#yammer"
  get "yammer/callback", to: "users/omniauth_callbacks#callback"

  post 'bot', to: 'push_messages#bot_answer'
  # get 'bot', to: 'push_messages#bot_answer'

  resources :groups, only: [:index, :show, :new, :create, :destroys] do
    resources :incentive_templates
    get 'change_incentive_template', to: 'incentive_templates#change'
    resources :push_messages, only: [:create]
  end

  resources :memberships, only: [:destroy]

  get 'demo', to: 'groups#demo'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  validates :name, presence: true, uniqueness: true
  validates :kind, presence: true, uniqueness: true
end

app/models/bot_user.rb
class BotUser < ApplicationRecord
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :incentive_templates

  has_many :messages, through: :thread_posts, dependent: :destroy

  has_many :thread_posts, dependent: :destroy

  has_many :user_badges
  has_many :badges, through: :badges

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates :full_name, presence: true

  def member?(user)
    Membership.exists? group: self, user: user
  end
end

app/models/incentive_template.rb
class IncentiveTemplate < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body, presence: true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :thread_post
  has_one :group, through: :thread_post

  before_save :kind

  private

  def kind
    self.idea_kint_kext_social = KindOfMessage.new(self.plain).call
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/push_message.rb
class PushMessage < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
end

app/models/push_post.rb
class PushPost < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
end

app/models/technip_to_wearestim_id.rb
class TechnipToWearestimId < ApplicationRecord
end

app/models/technip_user.rb
class TechnipUser < ApplicationRecord
end

app/models/thread_post.rb
class ThreadPost < ApplicationRecord
  belongs_to :group
  # belongs_to :user
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  has_one :bot_user, dependent: :destroy

  has_many :thread_posts, through: :groups
  has_many :messages, dependent: :destroy

  has_many :incentive_templates, dependent: :destroy

  has_many :push_messages, dependent: :destroy

  def self.find_for_yammer_oauth(auth)
    user_params = {
      access_token: auth["access_token"]["token"],
      rse_id: auth["access_token"]["user_id"],
      email: auth["user"]["email"],
      username: auth["user"]["name"],
      first_name: auth["user"]["first_name"],
      last_name: auth["user"]["last_name"],
      job_title: auth["user"]["job_ttle"],
      contact: auth["user"]["contact"],
      timezone: auth["user"]["timezone"],
      location: auth["user"]["location"],
      department: auth["user"]["department"],
      expertise: auth["user"]["expertise"],
      mugshot_url: auth["user"]["mugshot_url_template"].sub('{width}x{height}','400x400'),
      network_name: auth["user"]["network_name"]
    }

    user = User.where(email: auth["user"]["email"]).first

    if user
      # User already signed up -> update data?
      user.update(user_params)
    else
      # User does not not exists, we create it
      user = User.new(user_params)
      user.password = Devise.friendly_token[0, 20]
      user.save
    end

    return user
  end

end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
  belongs_to :group
end

app/controllers/groups_controller.rb
require 'yammer'

class GroupsController < ApplicationController
  before_action :find_group, only: [:show] # :destoy ?
  before_action :set_demo, only: [:show, :demo] # :destoy ?
  skip_before_action :authenticate_user!, only: [:demo]

  def index
    @groups     = policy_scope(Group)
    @group      = Group.new
    @yam_groups = Yammer::GetAllGroups.new(current_user).call
    @yam_groups = @yam_groups.select do |group|
      Membership.joins(:group).where('groups.full_name = ? and memberships.user_id = ? and memberships.user_in_dash = true', group[:full_name], current_user.id).empty?
    end
  end

  def show
    @push_default_value = {
      awards: awards,
      incentive: incentive
    }

    @push_message = PushMessage.new
  end

  def demo
    @demo = true
    @group = Group.find_by_full_name('Innovation Challenge - The Company')
    authorize @group

    @push_default_value = {
      awards: awards,
      incentive: incentive
    }

    #@push_message = PushMessage.new
  end

  def create
    yam_groups            = Yammer::GetAllGroups.new(current_user).call
    group_params_from_api = yam_groups.find do |yam_group|
      yam_group[:full_name] == params[:group][:full_name]
    end
    if Group.where('full_name = ?', group_params_from_api[:full_name]).empty?
      @group = current_user.groups.build(group_params_from_api)
      authorize @group
      @group.save
      # Yammer::UpdateGroup.new(current_user, @group).call
    else
      @group = Group.where('full_name = ?', group_params_from_api[:full_name]).first
      authorize @group
    end

    if Membership.where('user_id = ? and group_id = ?', current_user.id, @group.id).empty?
      Membership.create!(user: current_user, group: @group, user_in_dash: true)
    else
      membership = Membership.where('user_id = ? and group_id = ?', current_user.id, @group.id).first
      membership.user_in_dash = true
      membership.save
    end

    redirect_to groups_path
  end

  # def destroy
  # end

  private

  def find_group
    @group = Group.find(params[:id])
    authorize @group
  end

  def awards
    influencer = KpiDash.new(@group, 'influencer').call
    activist   = KpiDash.new(@group, 'activist').call
    networker  = KpiDash.new(@group, 'networker').call
    inventor   = KpiDash.new(@group, 'inventor').call
    mastermind = KpiDash.new(@group, 'mastermind').call
    "Special congratulations for this week :
    - The influencer: #{influencer[:user].first_name} #{influencer[:user].last_name.capitalize}
    - The activist: #{activist[:user].first_name} #{activist[:user].last_name.capitalize}
    - The networker: #{networker[:user].first_name} #{networker[:user].last_name.capitalize}
    - The inventor: #{inventor[:user].first_name} #{inventor[:user].last_name.capitalize}
    - The mastermind: #{mastermind[:user].first_name} #{mastermind[:user].last_name.capitalize}"
  end

  def incentive
    if IncentiveTemplate.all.count != 0
      incentive_template_sample = IncentiveTemplate.all.sample
      @incentive_template_id = incentive_template_sample.id
      incentive_template_sample.body
    end
  end

  def set_demo
    @demo = false
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :styleguide ]

  def home
  end

  def styleguide
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/groups/dashboard/general/_active_members_card.html.erb
<div class="grid-title">GENERAL ACTIVITY</div>
<div class="grid-content">
  <div class="grid-donut">
    <%= render 'groups/dashboard/general/retention_donut_chart' %>
  </div>
  <div class="like-row">
    <div class="badge-like likes-color">
      <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> <%= KpiDash.new(@group, 'likes').call %>
    </div>
    <div class="badge-like comments-color">
      <i class="fa fa-comment-o" aria-hidden="true"></i> <%= KpiDash.new(@group, 'comments').call %>
    </div>
  </div>
</div>

app/views/groups/dashboard/general/_badge.html.erb
<div class="badge-card">
  <div class="badge-reward text-center">
    <div class="badge-pictures">
      <%= image_tag mugshot_url, class: "avatar-badges" %>
      <img class="reward-picto" src="<%= path_to_image picture %>">
    </div>
    <h4><%= title %></h4>
    <p><%= description %></p>
    <p><%= name %></p>
  </div>
</div>

app/views/groups/dashboard/general/_comments_by_country_card.html.erb
<div class="grid-title">COMMENTS BY COUNTRY</div>

<div class="grid-content">
  <div id="comments_country_bar_chart">
    <div id="countries_bars" class="size-full"></div>
  </div>
</div>

<% content_for :after_js do %>
  <script type="text/javascript">
    function commentsCountryChart() {
      google.charts.load("current", {packages:['corechart']});
      google.charts.setOnLoadCallback(drawColumnChart);
      function drawColumnChart() {
        var data = google.visualization.arrayToDataTable(<%=
          countries = KpiDash.new(@group, 'countries').call
          chart_colors = Dashboard.bar_chart_colors(4)
          chart_title = ["Country", "Comments", { role: "style" }, { role: 'annotation' } ]

          chart_countries_comments = countries.each_with_index.map do |country, index|
            chart_country_array = []
            if country[:name] == 'United Kingdom'
              chart_country_array.push 'UK'
            else
              chart_country_array.push country[:name]
            end
            chart_country_array.push country[:comments]
            chart_country_array.push chart_colors[index]
            chart_country_array.push "#{country[:comments]} COMMENTS"
          end

          chart_countries_comments.unshift chart_title
          raw chart_countries_comments.to_json
        %>);

        var options = {
          fontName: 'Open Sans',
          chartArea: {
            width: '100%',
            height: '80%'
          },
          vAxis: {
            baselineColor: 'white',
            ticks: [],
            minValue: 0
          },
          hAxis: {
            baselineColor: 'none',
            ticks: [],
            textStyle: {
              color: 'white'
            }
          },
          backgroundColor: { fill:'transparent' },
          bar: {groupWidth: "85%"},
          legend: { position: "none" },
          animation: {
            duration: 2000,
            startup: true,
            easing: 'out',
          },
          annotations: {
            alwaysOutside: false,
            textStyle: {
              fontSize: 8,
              bold: true,
              opacity: 0.8
            }
          }
        };
        var chart = new google.visualization.ColumnChart(document.getElementById("countries_bars"));
        chart.draw(data, options);
      }
    }
  </script>
<% end %>

app/views/groups/dashboard/general/_departments_card.html.erb
<div class="grid-title">ACTIVITY BY DEPARTMENT</div>
<div class="grid-content">
  <div class="map-legend-box">
    <div>
      <p><em>Color density: active participants</em></p>
      <div class="map-legend-key">
        <div class="map-legend-min-max"><%=
          active_members = KpiDash.new(@group, 'departments').call
          nb_active_members = active_members.map { |department| department[:active_members] }
          nb_active_members_min = nb_active_members.min
          nb_active_members_max = nb_active_members.max
          nb_active_members_min == nb_active_members_max ? 0 : nb_active_members_min
        %></div>
        <div class="map-legend-key-color"></div>
        <div class="map-legend-min-max"><%=
          nb_active_members_max
        %></div>
      </div>
    </div>
  </div>

  <div id="department_members_polar" class="size-full z-10"></div>
</div>

<% content_for :after_js do %>
  <script type="text/javascript">
    function departmentChart() {
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        <%
          require 'matrix'
          begin_color_vector        = Dashboard.chart_density_vectors.first
          end_color_vector          = Dashboard.chart_density_vectors.last
          color_vector              = end_color_vector - begin_color_vector
          color_vector_norm         = color_vector.norm
          departments                = KpiDash.new(@group, 'departments').call
          min_comments_departments   = KpiDash.new(@group, 'departments').call.map { |department| department[:active_members] }.min
          max_comments_departments   = KpiDash.new(@group, 'departments').call.map { |department| department[:active_members] }.max
          depth_comments_departments = max_comments_departments - min_comments_departments

          background_colors = departments.map do |department|
            vector_color  = begin_color_vector + ((department[:active_members] - min_comments_departments) / depth_comments_departments.to_f) * color_vector
            "##{vector_color[0].round.to_s(16).rjust(2, '0')}#{vector_color[1].round.to_s(16).rjust(2, '0')}#{vector_color[2].round.to_s(16).rjust(2, '0')}"
          end
        %>

        var data = google.visualization.arrayToDataTable(<%=
          departments_comments = KpiDash.new(@group, 'departments').call
          chart_colors = background_colors
          chart_title = ["Department", "Comments"]

          chart_departments_comments = departments_comments.each_with_index.map do |department, index|
            chart_department_array = []
            chart_department_array.push department[:name]
            chart_department_array.push department[:comments]
          end

          chart_departments_comments.unshift chart_title
          raw chart_departments_comments.to_json
        %>);

        var options = {
          fontName: 'Open Sans',
          backgroundColor: { fill:'transparent' },
          pieHole: 0.6,
          pieSliceText: 'value',
          pieSliceTextStyle: { color: '<%= Dashboard.map_dataless_region_color %>' },
          pieSliceBorderColor: '#031421',
          legend: {
            position: 'labeled',
            textStyle: {
              color: 'white'
            }
          },
          animation: {
            duration: 2000,
            startup: true,
            easing: 'out',
          },
          slices: <%=
            chart_colors_hash = {}
            chart_colors.each_with_index do |color, index|
              chart_colors_hash[index] = {
                color: color
              }
            end
            raw chart_colors_hash.to_json
          %>
        };

        var chart = new google.visualization.PieChart(document.getElementById('department_members_polar'));
        chart.draw(data, options);
      }
    }
  </script>
<% end %>

app/views/groups/dashboard/general/_index.html.erb
<div class="row">
  <div class="grid-element col-xs-12 col-sm-12 col-md-4 col-lg-4 dam-color-1 grid-borders">
    <%= render 'groups/dashboard/general/active_members_card' %>
  </div>
  <div class="grid-element col-xs-12 col-sm-12 col-md-8 col-lg-8 dam-color-2 grid-borders" style="overflow: hidden">
    <%= render 'groups/dashboard/general/departments_card' %>
  </div>
</div>
<div class="row">
  <div class="grid-element col-xs-12 col-sm-12 col-md-8 col-lg-8 dam-color-2 grid-borders">
    <%= render 'groups/dashboard/general/members_map' %>
  </div>
  <div class="grid-element col-xs-12 col-sm-12 col-md-4 col-lg-4 dam-color-1 grid-borders">
    <%= render 'groups/dashboard/general/comments_by_country_card' %>
  </div>
</div>

app/views/groups/dashboard/general/_members_map.html.erb
<div class="grid-title">PARTICIPANTS BY COUNTRY</div>
<div class="size-full horizontal-vertical-center direction-column">
<div class="map-legend-box">
    <h4>Country ranking</h4>
    <ol>
      <% KpiDash.new(@group, 'countries').call[1..3].each do |country| %>
        <li><%= country[:name] %></li>
      <% end %>
    </ol>
    <div>
      <p><em>Color density: active participants</em></p>
      <div class="map-legend-key">
        <div class="map-legend-min-max"><%=
          active_members = KpiDash.new(@group, 'countries').call
          nb_active_members = active_members.map { |country| country[:active_members] }
          nb_active_members_min = nb_active_members.min
          nb_active_members_max = nb_active_members.max
          nb_active_members_min == nb_active_members_max ? 0 : nb_active_members_min
        %></div>
        <div class="map-legend-key-color"></div>
        <div class="map-legend-min-max"><%=
          nb_active_members_max
        %></div>
      </div>
    </div>
  </div>

  <div id="regions_div"></div>
</div>

<% content_for :after_js do %>
  <script>
    function geoChartMap() {
      google.charts.load('upcoming', {'packages':['geochart']});
      google.charts.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {

        var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

        var data = google.visualization.arrayToDataTable(<%=
          countries   = KpiDash.new(@group, 'countries').call
          chart_title = ['Country', 'Active members']

          chart_countries_active_members = countries.map do |country|
            chart_country_array = []
            chart_country_array.push country[:name]
            chart_country_array.push country[:active_members]
          end

          chart_countries_active_members.unshift chart_title
          raw chart_countries_active_members.to_json
        %>);

        var options = {
          fontName: 'Open Sans',
          backgroundColor: 'transparent',
          colorAxis: {colors: <%= raw Dashboard.chart_density_colors.to_json %> },
          datalessRegionColor: "<%= raw Dashboard.map_dataless_region_color %>", legend:'none'
        }

        chart.draw(data, options);
      }
    }
  </script>
<% end %>

app/views/groups/dashboard/general/_retention_donut_chart.html.erb
<div class="margin-auto position-relative retention-donut-size">
  <svg class="position-absolute width-full">
    <defs>
      <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" style="stop-color: <%= Dashboard.likes_color %>; stop-opacity:1" />
        <stop offset="100%" style="stop-color: <%= Dashboard.comments_color %>; stop-opacity:1" />
      </linearGradient>
    </defs>
  </svg>
<div id="retention-rate" class="position-absolute size-full z-10"></div>
  <div class="horizontal-vertical-center direction-column size-full z-1">
    <div class="donut-title text-center"><%= KpiDash.new(@group, 'members_ratio').call %> %</div>
    <div class="donut-subtitle text-center"><strong><%= KpiDash.new(@group, 'members_active').call %></strong> ACTIVE MEMBERS</div>
  </div>
</div>

<% content_for :after_js do %>
  <script type="text/javascript">
    function retentionChart() {
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable(<%=
          active_inactive_members = KpiDash.new(@group, 'members').call
          retention_chart = [
            ['Members', 'Number of members'],
            ['Active', active_inactive_members[:active]],
            ['Inactive', active_inactive_members[:inactive]]
          ]
          raw retention_chart.to_json
        %>);

        var options = {
          fontName: 'Open Sans',
          chartArea: {
            width: '90%',
            height: '90%'
          },
          pieHole: 0.9,
          pieSliceBorderColor: 'transparent',
          pieSliceText: 'none',
          animation: {
            duration: 5000,
            startup: true,
            easing: 'in',
          },
          legend: { position: "none" },
          backgroundColor: { fill:'transparent' },
          slices: {
            0: { color: '#5bc5f1' },
            1: { color: 'transparent' }
          }
        };

        var chart = new google.visualization.PieChart(document.getElementById('retention-rate'));
        google.visualization.events.addListener(chart, 'ready', allReady);
        google.visualization.events.addListener(chart, 'onmouseover', allReady);
        google.visualization.events.addListener(chart, 'onmouseout', allReady);
        chart.draw(data, options);
      }

      function allReady() {
        $("#retention-rate [fill='#5bc5f1']").attr('fill', 'url(#grad1)');
      }
    }
  </script>
<% end %>

app/views/groups/dashboard/innovation/_donut.html.erb
<div class="innovation-donut width-full">
  <div id=<%= donut_id %> class="innovation-donut-container"></div>
  <div class="innovation_donut_content">
    <i class="fa fa-<%= icon %> fa-fw" aria-hidden="true"></i>
  </div>
</div>

<%= content_for :after_js do %>
  <script type="text/javascript">
    function <%= donut_id %>() {
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(innovationChart);
      function innovationChart() {
        var data = google.visualization.arrayToDataTable(<%=
          innovation_chart_title = ['Type', 'Comments']
          innovation_division = KpiDash.new(@group, kpi).call
          innovation_legend = [
            'Innovation - B',
            'Disruption - B',
            'Innovation - T',
            'Disruption - T'
          ]

          innovation_data = innovation_division.each_with_index.map do |division, index|
            [innovation_legend[index], innovation_division[index]]
          end

          innovation_data.unshift innovation_chart_title
          raw innovation_data.to_json
        %>);

        var options = {
          fontName: 'Open Sans',
          chartArea: {
            width: '90%',
            height: '90%'
          },
          <%=
            # if kpi == 'innovation_kint'
              raw "legend: {
                  position: 'labeled',
                  textStyle: {
                    color: 'white',
                    fontSize: 8
                  }
                },"
            # else
            #   raw "legend: { position: 'none' },"
            # end
          %>
          pieSliceText: 'none',
          pieHole: 0.85,
          pieSliceBorderColor: 'transparent',
          animation: {
            duration: 5000,
            startup: true,
            easing: 'in',
          },
          backgroundColor: { fill:'transparent' },
          slices: {
            0: { color: '<%= Dashboard.innovation_donuts_colors[:business_innovation] %>' },
            1: { color: '<%= Dashboard.innovation_donuts_colors[:business_disruption] %>' },
            2: { color: '<%= Dashboard.innovation_donuts_colors[:technology_innovation] %>' },
            3: { color: '<%= Dashboard.innovation_donuts_colors[:technology_disruption] %>' }
          }
        };

        var chart = new google.visualization.PieChart(document.getElementById("<%= donut_id %>"));
        chart.draw(data, options);
      }
    }
  </script>
<% end %>

app/views/groups/dashboard/organization/_index.html.erb
<div class="row width-full height-full">
  <div class="col-xs-12 col-sm-6 height-full organization_column">
    <div class="position-absolute width-full horizontal-vertical-center organization_title business-bg-color color-white">ADHESION ON BUSINESS TOPICS</div>
    <div class="width-full organisation-column-container">
      <div class="dam-color-1 organisation_content grid-borders">
        <%= render 'groups/dashboard/organization/business_likes_comments' %>
      </div>
      <div class="dam-color-2 organisation_content grid-borders">
        <%= render 'groups/dashboard/organization/business_countries_departments' %>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 height-full organization_column">
    <div class="position-absolute width-full horizontal-vertical-center organization_title technology-bg-color color-white">ADHESION ON TECHNOLOGICAL TOPICS</div>
    <div class="width-full organisation-column-container">
      <div class="dam-color-2 organisation_content grid-borders">
        <%= render 'groups/dashboard/organization/tech_likes_comments' %>
      </div>
      <div class="dam-color-1 organisation_content grid-borders">
        <%= render 'groups/dashboard/organization/tech_countries_departments' %>
      </div>
    </div>
  </div>
</div>

app/views/groups/dashboard/push/_push_form.html.erb
<% if @demo %>
  <%= simple_form_for [@group] do |f| %>
    <div class="panel-default">
      <div class="panel-heading">
        <div>
          <%= image_tag 'Timothée GARCIA.png', class: "avatar-square" %>
        </div>
        <div class="panel-title">
          <div><%= @group.full_name %></div>
          <div>Just now</div>
        </div>
      </div>
        <div class="panel-body">
          <%= f.input :type, as: :hidden, input_html: { value: push.to_s } %>
          <%= f.input :body, as: :text, label: false, input_html: { cols: 40, rows: 8, class: "form-control textarea-push-message", value: @push_default_value[push] } %>
          <div class="form-img-container text-center dam-color-3">
          <img class="img-message" src="<%= path_to_image "congrats-blanc.png" %>">
          </div>
        </div>
      <div class="panel-footer">
        <div class="form-group">
          <div class="button-holder">
            <%= link_to '<i class="fa fa-refresh" aria-hidden="true"></i>'.html_safe, group_change_incentive_template_path(@group, @incentive_template_id), remote: true %>
            <div class="submit-button text-center">
              <div class="fa fa-check post-done hidden"></div>
              <div class="loading hidden"></div>
              <div class="btn button-post">Create Push post</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <%= simple_form_for [@group, @push_message] do |f| %>
    <div class="panel-default">
      <div class="panel-heading">
        <div>
          <%= image_tag current_user.mugshot_url, class: "avatar-square" %>
        </div>
        <div class="panel-title">
          <div><%= @group.full_name %></div>
          <div>Just now</div>
        </div>
      </div>
        <div class="panel-body">
          <%= f.input :type, as: :hidden, input_html: { value: push.to_s } %>
          <%= f.input :body, as: :text, label: false, input_html: { cols: 40, rows: 8, class: "form-control textarea-push-message", value: @push_default_value[push] } %>
          <div class="form-img-container text-center dam-color-3">
          <img class="img-message" src="<%= path_to_image "congrats-blanc.png" %>">
          </div>
        </div>
      <div class="panel-footer">
        <div class="form-group">
          <div class="button-holder">
            <%= link_to '<i class="fa fa-refresh" aria-hidden="true"></i>'.html_safe, group_change_incentive_template_path(@group, @incentive_template_id), remote: true %>
            <div class="submit-button text-center">
              <div class="fa fa-check post-done hidden"></div>
              <div class="loading hidden"></div>
              <%= f.button :button, "Create Push post", class: "btn button-post" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<% content_for :after_js do %>
  <script>
    $(function() {
      $(".button-post").click(function() {
        var button, parent;
        button = $(this)
        parent  = $(this).parent();

        button.addClass("hidden");
        parent.find(".loading").removeClass("hidden");
        $('.loading:focus').blur()

        setTimeout(function() {
          parent.find(".loading").addClass("hidden");
          parent.find(".post-done").removeClass("hidden");
          parent.find(".post-done").addClass("finish");
        }, 1000);

        setTimeout(function() {
          parent.find(".post-done").removeClass("finish");
        }, 2000);

        setTimeout(function() {
          parent.find(".post-done").addClass("hidden");
          button.removeClass("hidden");
        }, 2500);
      })

      $(".fa-refresh").click(function() {
        $(this).addClass("fa-spin");
        button = $(this)

        setTimeout(function() {
        button.removeClass("fa-spin");
        }, 1050);
      })
    });
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>