config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'groups#index'
  end

  root to: 'pages#home'

  post "yammer", to: "users/omniauth_callbacks#yammer"
  get "yammer/callback", to: "users/omniauth_callbacks#callback"

  post 'bot', to: 'push_messages#bot_answer'
  # get 'bot', to: 'push_messages#bot_answer'

  resources :groups, only: [:index, :show, :new, :create, :destroys] do
    resources :incentive_templates
    get 'change_incentive_template', to: 'incentive_templates#change'
    resources :push_messages, only: [:create]
  end

  resources :memberships, only: [:destroy]

  get 'demo', to: 'groups#demo'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :incentive_templates

  has_many :messages, through: :thread_posts, dependent: :destroy

  has_many :thread_posts, dependent: :destroy

  has_many :user_badges
  has_many :badges, through: :badges

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates :full_name, presence: true

  def member?(user)
    Membership.exists? group: self, user: user
  end
end

app/controllers/groups_controller.rb
require 'yammer'

class GroupsController < ApplicationController
  before_action :find_group, only: [:show] # :destoy ?
  before_action :set_demo, only: [:show, :demo] # :destoy ?
  skip_before_action :authenticate_user!, only: [:demo]

  def index
    @groups     = policy_scope(Group)
    @group      = Group.new
    @yam_groups = Yammer::GetAllGroups.new(current_user).call
    @yam_groups = @yam_groups.select do |group|
      Membership.joins(:group).where('groups.full_name = ? and memberships.user_id = ? and memberships.user_in_dash = true', group[:full_name], current_user.id).empty?
    end
  end

  def show
    @push_default_value = {
      awards: awards,
      incentive: incentive
    }

    @push_message = PushMessage.new
  end

  def demo
    @demo = true
    @group = Group.find_by_full_name('Innovation Challenge - The Company')
    authorize @group

    @push_default_value = {
      awards: awards,
      incentive: incentive
    }

    #@push_message = PushMessage.new
  end

  def create
    yam_groups            = Yammer::GetAllGroups.new(current_user).call
    group_params_from_api = yam_groups.find do |yam_group|
      yam_group[:full_name] == params[:group][:full_name]
    end
    if Group.where('full_name = ?', group_params_from_api[:full_name]).empty?
      @group = current_user.groups.build(group_params_from_api)
      authorize @group
      @group.save
      # Yammer::UpdateGroup.new(current_user, @group).call
    else
      @group = Group.where('full_name = ?', group_params_from_api[:full_name]).first
      authorize @group
    end

    if Membership.where('user_id = ? and group_id = ?', current_user.id, @group.id).empty?
      Membership.create!(user: current_user, group: @group, user_in_dash: true)
    else
      membership = Membership.where('user_id = ? and group_id = ?', current_user.id, @group.id).first
      membership.user_in_dash = true
      membership.save
    end

    redirect_to groups_path
  end

  # def destroy
  # end

  private

  def find_group
    @group = Group.find(params[:id])
    authorize @group
  end

  def awards
    influencer = KpiDash.new(@group, 'influencer').call
    activist   = KpiDash.new(@group, 'activist').call
    networker  = KpiDash.new(@group, 'networker').call
    inventor   = KpiDash.new(@group, 'inventor').call
    mastermind = KpiDash.new(@group, 'mastermind').call
    "Special congratulations for this week :
    - The influencer: #{influencer[:user].first_name} #{influencer[:user].last_name.capitalize}
    - The activist: #{activist[:user].first_name} #{activist[:user].last_name.capitalize}
    - The networker: #{networker[:user].first_name} #{networker[:user].last_name.capitalize}
    - The inventor: #{inventor[:user].first_name} #{inventor[:user].last_name.capitalize}
    - The mastermind: #{mastermind[:user].first_name} #{mastermind[:user].last_name.capitalize}"
  end

  def incentive
    if IncentiveTemplate.all.count != 0
      incentive_template_sample = IncentiveTemplate.all.sample
      @incentive_template_id = incentive_template_sample.id
      incentive_template_sample.body
    end
  end

  def set_demo
    @demo = false
  end
end

app/views/groups/_idea.html.erb
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 54 54" style="enable-background:new 0 0 54 54;" xml:space="preserve">

<defs>
  <linearGradient id="gradient">
    <stop offset="5%" stop-color="#FFC338" />
    <stop offset="95%" stop-color="#FFEA68" />
  </linearGradient>
</defs>
	<path fill="url(#gradient)" d="M27,8c-9.374,0-17,7.626-17,17c0,7.112,4.391,13.412,11,15.9V50c0,0.553,0.447,1,1,1h1v2c0,0.553,0.447,1,1,1h6
		c0.553,0,1-0.447,1-1v-2h1c0.553,0,1-0.447,1-1v-9.1c6.609-2.488,11-8.788,11-15.9C44,15.626,36.374,8,27,8z M30,49
		c-0.553,0-1,0.447-1,1v2h-4v-2c0-0.553-0.447-1-1-1h-1v-5h8v5H30z M31.688,39.242C31.277,39.377,31,39.761,31,40.192V42h-8v-1.808
		c0-0.432-0.277-0.815-0.688-0.95C16.145,37.214,12,31.49,12,25c0-8.271,6.729-15,15-15s15,6.729,15,15
		C42,31.49,37.855,37.214,31.688,39.242z"/>
	<path d="M27,6c0.553,0,1-0.447,1-1V1c0-0.553-0.447-1-1-1s-1,0.447-1,1v4C26,5.553,26.447,6,27,6z"/>
	<path d="M51,24h-4c-0.553,0-1,0.447-1,1s0.447,1,1,1h4c0.553,0,1-0.447,1-1S51.553,24,51,24z"/>
	<path d="M7,24H3c-0.553,0-1,0.447-1,1s0.447,1,1,1h4c0.553,0,1-0.447,1-1S7.553,24,7,24z"/>
	<path d="M43.264,7.322l-2.828,2.828c-0.391,0.391-0.391,1.023,0,1.414c0.195,0.195,0.451,0.293,0.707,0.293
		s0.512-0.098,0.707-0.293l2.828-2.828c0.391-0.391,0.391-1.023,0-1.414S43.654,6.932,43.264,7.322z"/>
	<path d="M12.15,38.436l-2.828,2.828c-0.391,0.391-0.391,1.023,0,1.414c0.195,0.195,0.451,0.293,0.707,0.293
		s0.512-0.098,0.707-0.293l2.828-2.828c0.391-0.391,0.391-1.023,0-1.414S12.541,38.045,12.15,38.436z"/>
	<path d="M41.85,38.436c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414l2.828,2.828c0.195,0.195,0.451,0.293,0.707,0.293
		s0.512-0.098,0.707-0.293c0.391-0.391,0.391-1.023,0-1.414L41.85,38.436z"/>
	<path d="M12.15,11.564c0.195,0.195,0.451,0.293,0.707,0.293s0.512-0.098,0.707-0.293c0.391-0.391,0.391-1.023,0-1.414l-2.828-2.828
		c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414L12.15,11.564z"/>
	<path d="M27,13c-6.617,0-12,5.383-12,12c0,0.553,0.447,1,1,1s1-0.447,1-1c0-5.514,4.486-10,10-10c0.553,0,1-0.447,1-1
		S27.553,13,27,13z"/>
</svg>

app/views/groups/_modal_form_create_group.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Create a new challenge</h4>
      </div>
      <div class="modal-body">
        <div>
          <%= simple_form_for @group do |f| %>
            <%= f.input :full_name,
              collection: @yam_groups.map { |yam_group| yam_group[:full_name] },
              selected: @yam_groups.first[:full_name], label: false  %>
            <%= f.button :button, "Create Group", class: "btn btn-primary margin-top-two", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Creating a group..."} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/demo.html.erb
<div id="wrapper">
  <%= render 'groups/dashboard/sidebar' %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <section id="general" class="margin-top">
          <div class="text-center section-title"><i class="fa fa-tachometer" aria-hidden="true"></i>&nbsp;GENERAL ACTIVITY</div>
          <%= render 'groups/dashboard/general/index' %>
        </section>
      </div>
      <div class="row">
        <section id="badges">
          <div class="text-center section-title"><i class="fa fa-user-circle-o" aria-hidden="true"></i>&nbsp;AWARDS</div>
          <%= render 'groups/dashboard/badges/index' %>
        </section>
      </div>
      <div class="row">
        <section id="organization">
          <div class="text-center section-title"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;ORGANISATION IMPACT</div>
          <%= render 'groups/dashboard/organization/index' %>
        </section>
      </div>
      <div class="row">
        <section id="innovation">
          <div class="text-center section-title"><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;INNOVATION CAPACITY</div>
          <%= render 'groups/dashboard/innovation/index' %>
        </section>
      </div>
      <div class="row">
        <section id="push">
          <div class="text-center section-title"><i class="fa fa-check" aria-hidden="true"></i>&nbsp;PUSH MESSAGES</div>
          <%= render 'groups/dashboard/push/index' %>
        </section>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    if ( window.location.hash ) scroll(0,0);
    setTimeout( function() { scroll(0,0); }, 1 );

    $( function(){
      if(window.location.hash) {
          var anchor = window.location.hash
          $('.tab.active').removeClass("active");
          $('a[href="' + anchor + '"]').addClass("active");
          // smooth scroll to the anchor id
          $('html, body').animate({
              scrollTop: $(window.location.hash).offset().top - 40
          }, 1000, 'swing');
      }
    } )
  </script>
<% end %>

app/views/groups/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.5) 50%), url('<%= path_to_image "background.jpg" %>');">
  <div class="container margin-top padded home home-font-shadow" >
    <div class="group-title">
      <h1>Welcome <%= @current_user.first_name + " " + @current_user.last_name %></h1>
      <p>Pick a challenge or create a new one</p>
    </div>
    <div class="row">
      <% @groups.reverse.each do |group| %>
        <div class="col-xs-12 col-sm-4" data-membership-id="<%= Membership.where(group: group, user: current_user).first.id %>">
          <%= link_to membership_path(Membership.where(group: group, user: current_user).first), class: "card-icon", method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          <% end %>
          <%= link_to group_path(group), class: 'card-group-a' do %>
            <div class="card-group" style="background-image: linear-gradient(to bottom left, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.6) 50%), url('<%= path_to_image "background-2.jpg" %>');">
              <div class="card-group-description ">
                <div class="card-group-picture-absolute">
                  <%= image_tag group.mugshot_url, class: "card-group-avatar" %>
                </div>
                <h2><%= group.full_name %></h2>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <%= unless @yam_groups.empty?
        link_to '', 'data-toggle' => 'modal', 'data-target' => '#myModal' do %>
          <div class="col-xs-12 col-sm-4">
            <div class="card-group card-group-btn">
              <div class="plus-lg">+</div>
              <div style="margin-top: -20px;">New challenge</div>
            </div>
          </div>
        <% end
      end %>
    </div>
  </div>
</div>

<%=
unless @yam_groups.empty?
  render 'modal_form_create_group'
end
%>

app/views/groups/show.html.erb
<div id="wrapper">
  <%= render 'groups/dashboard/sidebar' %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <section id="general" class="margin-top">
          <div class="text-center section-title"><i class="fa fa-tachometer" aria-hidden="true"></i>&nbsp;GENERAL ACTIVITY</div>
          <%= render 'groups/dashboard/general/index' %>
        </section>
      </div>
      <div class="row">
        <section id="badges">
          <div class="text-center section-title"><i class="fa fa-user-circle-o" aria-hidden="true"></i>&nbsp;AWARDS</div>
          <%= render 'groups/dashboard/badges/index' %>
        </section>
      </div>
      <div class="row">
        <section id="organization">
          <div class="text-center section-title"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;ORGANISATION IMPACT</div>
          <%= render 'groups/dashboard/organization/index' %>
        </section>
      </div>
      <div class="row">
        <section id="innovation">
          <div class="text-center section-title"><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;INNOVATION CAPACITY</div>
          <%= render 'groups/dashboard/innovation/index' %>
        </section>
      </div>
      <div class="row">
        <section id="push">
          <div class="text-center section-title"><i class="fa fa-check" aria-hidden="true"></i>&nbsp;PUSH MESSAGES</div>
          <%= render 'groups/dashboard/push/index' %>
        </section>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    if ( window.location.hash ) scroll(0,0);
    setTimeout( function() { scroll(0,0); }, 1 );

    $( function(){
      if(window.location.hash) {
          var anchor = window.location.hash
          $('.tab.active').removeClass("active");
          $('a[href="' + anchor + '"]').addClass("active");
          // smooth scroll to the anchor id
          $('html, body').animate({
              scrollTop: $(window.location.hash).offset().top - 40
          }, 1000, 'swing');
      }
    } )
  </script>
<% end %>